/*
 * Begin Program
 */
package learn;
import java.util.Random;
import java.lang.Math;

/**
 * @author Kyle
 */
public class FFBG_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form FFBG_Calculator
     */
    public FFBG_Calculator() {
        initComponents();
    }
    
    public int parse_int(String the_string) {
        int the_int;        
        try {
            the_int = Integer.parseInt(the_string); 
        } catch(Exception e) {
            the_int = -1;
        }
            
        return the_int;
    }
    
    public int[] roll_Atk(javax.swing.JTextField Atk, javax.swing.JTextField d20in, javax.swing.JTextField Def) {
        int d20;
        if (d20_check.isSelected()) {
            Random rnd = new Random();
            rnd.setSeed(System.nanoTime());
            d20 = rnd.nextInt(20) + 1;
        } else {
            String text = d20in.getText();
            d20 = parse_int(text);
        }
  
        //Attack Dmg
        int atk = parse_int(Atk.getText());
        int def = parse_int(Def.getText());
        int damage;
        if (atk != -1 & def != -1 & d20 != -1) {
            damage = (int)( Math.pow(atk, 2.0) / def * d20 / 10);
        } else {
            damage = -1;
        }
        int ret[] = new int[2];
        ret[0] = damage;
        ret[1] = d20;
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atk1 = new javax.swing.JTextField();
        Result1 = new javax.swing.JLabel();
        Calc1 = new javax.swing.JButton();
        Mag2 = new javax.swing.JTextField();
        Def1 = new javax.swing.JTextField();
        Spr2 = new javax.swing.JTextField();
        AttackDmg = new javax.swing.JLabel();
        MagicDmg = new javax.swing.JLabel();
        Result2 = new javax.swing.JLabel();
        d20_1 = new javax.swing.JTextField();
        d20_2 = new javax.swing.JTextField();
        AtkStat_col = new javax.swing.JLabel();
        DefStat_col = new javax.swing.JLabel();
        Calc2 = new javax.swing.JButton();
        d20_check = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Celcius Converter");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Atk1.setText("Unit Atk");
        Atk1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Atk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Atk1MouseClicked(evt);
            }
        });

        Result1.setText("Result");

        Calc1.setText("Calc");
        Calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc1ActionPerformed(evt);
            }
        });

        Mag2.setText("Unit Mag");
        Mag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mag2MouseClicked(evt);
            }
        });

        Def1.setText("Enemy Def");
        Def1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Def1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Def1MouseClicked(evt);
            }
        });

        Spr2.setText("Enemy Spr");
        Spr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Spr2MouseClicked(evt);
            }
        });

        AttackDmg.setText("Attack Dmg");

        MagicDmg.setText("Magic Dmg");

        Result2.setText("Result");

        d20_1.setText("d20");
        d20_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        d20_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d20_1MouseClicked(evt);
            }
        });

        d20_2.setText("d20");
        d20_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        d20_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d20_2MouseClicked(evt);
            }
        });

        AtkStat_col.setText("Atk Stat");

        DefStat_col.setText("Def Stat");

        Calc2.setText("Calc");
        Calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc2ActionPerformed(evt);
            }
        });

        d20_check.setText("Auto Roll");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MagicDmg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mag2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d20_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Atk1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AtkStat_col, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d20_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d20_check))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DefStat_col, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Def1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(AttackDmg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Calc2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DefStat_col)
                    .addComponent(d20_check)
                    .addComponent(AtkStat_col))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AttackDmg)
                        .addComponent(Atk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d20_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Def1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result1)
                            .addComponent(Calc1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Spr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result2)
                            .addComponent(d20_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc2)
                            .addComponent(Mag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MagicDmg))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc1ActionPerformed
        int ret[] = roll_Atk(Atk1, d20_1, Def1);
        int damage = ret[0];
        int d20 = ret[1];
        
        if (damage != -1) {
            Result1.setText(String.valueOf(damage));
        } else {
            Result1.setText("Error");
        }
        
        if (d20_check.isSelected()) {
            d20_1.setText(String.valueOf(d20));
        }                
    }//GEN-LAST:event_Calc1ActionPerformed

    private void Def1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Def1MouseClicked
        String text = Def1.getText();
        if (text.equals("Enemy Def")) {
            Def1.setText("");
        }
    }//GEN-LAST:event_Def1MouseClicked

    private void Atk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atk1MouseClicked
        String text = Atk1.getText();
        if (text.equals("Unit Atk")) {
            Atk1.setText("");
        }
    }//GEN-LAST:event_Atk1MouseClicked

    private void Mag2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mag2MouseClicked
        String text = Mag2.getText();
        if (text.equals("Unit Mag")) {
            Mag2.setText("");
        }
    }//GEN-LAST:event_Mag2MouseClicked

    private void Spr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Spr2MouseClicked
        String text = Spr2.getText();
        if (text.equals("Enemy Spr")) {
            Spr2.setText("");
        }
    }//GEN-LAST:event_Spr2MouseClicked

    private void d20_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d20_1MouseClicked
        String text = d20_1.getText();
        if (text.equals("d20")) {
            d20_1.setText("");
        }
    }//GEN-LAST:event_d20_1MouseClicked

    private void d20_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d20_2MouseClicked
        String text = d20_2.getText();
        if (text.equals("d20")) {
            d20_2.setText("");
        }
    }//GEN-LAST:event_d20_2MouseClicked

    private void Calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc2ActionPerformed
        int ret[] = roll_Atk(Mag2, d20_2, Spr2);
        int damage = ret[0];
        int d20 = ret[1];
        
        if (damage != -1) {
            Result2.setText(String.valueOf(damage));
        } else {
            Result2.setText("Error");
        }
        
        if (d20_check.isSelected()) {
            d20_2.setText(String.valueOf(d20));
        }    
    }//GEN-LAST:event_Calc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFBG_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFBG_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFBG_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFBG_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFBG_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Atk1;
    private javax.swing.JLabel AtkStat_col;
    private javax.swing.JLabel AttackDmg;
    private javax.swing.JButton Calc1;
    private javax.swing.JButton Calc2;
    private javax.swing.JTextField Def1;
    private javax.swing.JLabel DefStat_col;
    private javax.swing.JTextField Mag2;
    private javax.swing.JLabel MagicDmg;
    private javax.swing.JLabel Result1;
    private javax.swing.JLabel Result2;
    private javax.swing.JTextField Spr2;
    private javax.swing.JTextField d20_1;
    private javax.swing.JTextField d20_2;
    private javax.swing.JCheckBox d20_check;
    // End of variables declaration//GEN-END:variables
}
